[tools]
godot = "latest"
pre-commit = "latest"
zlint = "latest"
usage = "latest"
zig = "0.15.2"
zls = "0.15.0"

[alias]
godot = "asdf:https://github.com/mkungla/asdf-godot"
zlint = "ubi:DonIsaac/zlint"

[tasks."docs:build"]
run = "zig build docs"

[tasks."docs:serve"]
dir = "zig-out/docs"
depends = ["docs:build"]
run = "mise exec bun -- bunx -y node-static ."
